### ISSUE TITLE
method-override for DELETE routing.

### ISSUE THREAD

**Issue by FL33s** [Colt/YelpCamp#22]
Hi. method-override isn't working for the DELETE routing. Does anyone have a solution to this issue? Thanks.

**Comment by Dango001** [comment]
Can you show your routes code and ejs template?

**Comment by FL33s** [comment]
Hi. Thanks for the reply. I've figured it out. Through trial and error at the time I just removed a slash from my res.render on my delete route. It's frustrating sometimes but we learn from the bugs in our code!
