### ISSUE TITLE
Cloudinary and multer-storage-cloudinary libraries not able to install as they a re no longer maintained, sharing the photo of the errors generated ,need a fix asap!!!

### ISSUE THREAD

**Issue by KD4222** [Colt/YelpCamp#31]
![cloudinary error](https://user-images.githubusercontent.com/71634102/185906964-11ace13e-78b6-4c5e-bf19-3a2104273523.jpg)
Please show some other way, for ex. doing this using aws-s3 bucket please! i am fed up and stuck at this issue from the last ten days.

**Comment by Aryan3212** [comment]
This isn't an issue with multer-storage-cloudinary. It has to do with the version of core-js in your environment. You should read the error message more carefully. Some fixes could include reinstalling everything in your environment including NodeJS.

**Comment by KD4222** [comment]
Hi fellow coders,
earlier i thought this issue had arised due to some local environment core-js version problem and that might be true in some cases but when i tried to go around it and extensively searched the web for solution, i still wasn't able to rectify this error and had to use an alternate service instead of cloudinary, the AWS S3 bucket. Though few days later, i found to my surprise that this problem had a very trivial solution in my case. I was able to install the above mentioned packages successfully just by using PowerShell instead of git bash. So , this was a classic example of searching for something everywhere when it was actually in front of you the whole time.

**Comment by Aryan3212** [comment]
Just putting this here so that people aren't confused when they stumble across the same issue. This probably has to do with other problems rather than using a different shell. For example, maybe Git Bash wasn't configured with the necessary permissions, or the PATH environment variable wasn't available to it and so on and so forth.
