### ISSUE TITLE
Error using Joi Validation Middleware

### ISSUE THREAD

**Issue by TalibIbrahim** [Colt/YelpCamp#38]
I used Joi validation and it worked perfectly the last time I worked on the project. The next video had a middleware made from it and nothing works after that. I even reverted back to my previous code and it still doesnt work. 

First while using the middleware i got an error saying 'cannot read properties of undefined reading('validate')' at my validateCampground function. 

Then I made some changes to the code and it said that " 'campground' is required" .

![image](https://user-images.githubusercontent.com/112410392/221540269-08f63d42-b6d4-4735-8b45-29ad61ddf63a.png)

Now, even when all of the inputs pass the validation, it still shows the above error.

I remove the validateCampground middleware, everything works fine. I even checked the documentation and couldnt find the problem anywhere.

**Comment by TalibIbrahim** [comment]
Also note that app.js: 130:13 refers to **_new_** in  **throw new ExpressError(msg,400)**

**Comment by Code-Singh** [comment]
I had the same error and the cause was enctype="multipart/form-data" attribute on my forms.
